# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-09 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParmaPass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.CharField(default=' ', max_length=10, verbose_name='查询请求字符串')),
            ],
            options={
                'verbose_name': '查询参数',
                'verbose_name_plural': '查询参数',
                'db_table': 'tb_text',
            },
        ),
    ]
