# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_auto_20191209_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicnum',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='默认图片'),
        ),
    ]
